#!/usr/bin/env bash

# Temp workspace
# switch workspace from one output to other
# for ex.
# focused = 1; unfocused = 2;
# switch focused, unfocused:
# temp = focused; focused = unfocused; unfocused = temp;

focused=$(i3-msg -t get_workspaces | jq | tr -d ,  | grep -A1 -B1 \"visible\"\:\ true | grep -B2 \"focused\"\:\ true | awk -F\  '{ print $2 }' | head -n1)
unfocused=$(i3-msg -t get_workspaces | jq | tr -d ,  | grep -A1 -B1 \"visible\"\:\ true | grep -B2 \"focused\"\:\ false | awk -F\  '{ print $2 }' | head -n1)

i3-msg workspace "TEMP" output "DVI-D-0"
i3-msg workspace "TEMP"

i3-msg workspace $focused
i3-msg move workspace to workspace "TEMP"

i3-msg workspace $unfocused
i3-msg move workspace to workspace $focused

i3-msg workspace "TEMP"
i3-msg move workspace to workspace $unfocused

i3-msg workspace $focused


i3-msg move workspace TEMP && i3-msg workspace $(i3-msg -t get_workspaces | jq | tr -d ,  | grep -A1 -B1 \"visible\"\:\ true | grep -B2 \"focused\"\:\ true | awk -F\  '{ print $2 }' | head -n1)
